<?php

namespace Database\Seeders;

use App\Models\AttendanceSetting;
use App\Models\Company;
use App\Models\Division;
use App\Models\Position;
use App\Models\Role;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class CabangSurabayaDummySeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Membuat Cabang ke-4 (Kantor Cabang Surabaya) beserta 50 karyawan
     * terstruktur lengkap (Pimpinan Cabang, 6 Supervisor, dan 43 Staff).
     */
    public function run(): void
    {
        $company = Company::first();
        if (! $company) {
            $company = Company::create([
                'name'      => 'PT Maju Bersama',
                'email'     => 'info@majubersama.co.id',
                'phone'     => '021-5555-1234',
                'address'   => 'Jl. Sudirman No. 10, Jakarta Selatan',
                'is_active' => true,
            ]);
        }

        $this->command?->info("🏢 Menyiapkan Kantor Cabang ke-4 untuk {$company->name}...");

        // ─── 1. Buat / Update Kantor Cabang ke-4 (Kantor Cabang Surabaya) ───
        $branch = AttendanceSetting::updateOrCreate(
            [
                'company_id'  => $company->id,
                'office_name' => 'Kantor Cabang Surabaya',
            ],
            [
                'office_latitude'              => -7.26250000,
                'office_longitude'             => 112.74310000,
                'radius_meters'                => 100,
                'work_start_time'              => '08:00:00',
                'work_end_time'                => '17:00:00',
                'break_minutes'                => 60,
                'work_days'                    => [1, 2, 3, 4, 5],
                'custom_schedules'             => [
                    '5' => [
                        'start'         => '08:00',
                        'end'           => '17:00',
                        'break_minutes' => 90,
                    ],
                ],
                'late_tolerance_minutes'       => 15,
                'late_checkin_cutoff_minutes'  => 120,
                'require_selfie'               => false,
                'allow_wfh'                    => true,
                'wfh_checkin_window_minutes'   => 120,
                'overtime_enabled'             => true,
                'min_overtime_minutes'         => 30,
                'early_leave_tolerance_minutes'=> 30,
                'min_checkout_interval_minutes'=> 10,
                'checkout_reminder_minutes'    => 30,
                'auto_checkout_grace_minutes'  => 60,
                'enforce_weekly_hours'         => true,
                'max_weekly_hours'             => 40,
                'shift_notice_days'            => 2,
                'default_leave_quota'          => 12,
                'leave_reset_date'             => '12-01',
                'last_leave_reset_on'          => '2025-12-01',
            ]
        );

        $this->command?->info("✅ Cabang dibuat: ID {$branch->id} - {$branch->office_name} (Lat: {$branch->office_latitude}, Lng: {$branch->office_longitude})");

        // ─── 2. Pastikan Divisi Utama Tersedia ───
        $divisionsData = [
            'OPER' => ['name' => 'Operations', 'description' => 'Operasional kantor cabang dan layanan lapangan'],
            'SALE' => ['name' => 'Sales', 'description' => 'Penjualan, akuisisi pelanggan, dan account management'],
            'LOGI' => ['name' => 'Logistics & Warehouse', 'description' => 'Gudang, persediaan barang, dan ekspedisi'],
            'FINA' => ['name' => 'Finance & Accounting', 'description' => 'Keuangan, kasir cabang, akuntansi, dan reimbursement'],
            'MARK' => ['name' => 'Marketing', 'description' => 'Pemasaran produk, promosi cabang, dan branding'],
            'HRGA' => ['name' => 'Human Resources & General Affairs', 'description' => 'SDM, kepatuhan absensi, dan operasional umum'],
            'IT'   => ['name' => 'Information Technology', 'description' => 'Infrastruktur IT, jaringan cabang, dan helpdesk'],
        ];

        $divisions = [];
        foreach ($divisionsData as $code => $data) {
            $division = Division::firstOrCreate(
                ['company_id' => $company->id, 'code' => $code],
                [
                    'name'        => $data['name'],
                    'description' => $data['description'],
                    'is_active'   => true,
                ]
            );
            $divisions[$code] = $division;
        }

        // ─── 3. Pastikan Posisi / Jabatan Tersedia ───
        $positionsData = [
            // Pimpinan Cabang
            'Branch Manager' => [
                'division'      => null,
                'is_supervisor' => true,
                'description'   => 'Pimpinan tertinggi operasional dan bisnis kantor cabang',
            ],
            // Operations
            'Operational Supervisor' => [
                'division'      => 'OPER',
                'is_supervisor' => true,
                'description'   => 'Supervisi proses operasional harian cabang dan tim lapangan',
            ],
            'Field Operations Lead' => [
                'division'      => 'OPER',
                'is_supervisor' => false,
                'description'   => 'Koordinator pelaksanaan tugas lapangan cabang',
            ],
            'Senior Staff Operasional' => [
                'division'      => 'OPER',
                'is_supervisor' => false,
                'description'   => 'Senior pelaksana proses operasional cabang',
            ],
            'Staff Operasional' => [
                'division'      => 'OPER',
                'is_supervisor' => false,
                'description'   => 'Pelaksana harian tugas operasional cabang',
            ],
            'Customer Service & Resepsionis' => [
                'division'      => 'OPER',
                'is_supervisor' => false,
                'description'   => 'Pelayanan tamu, front desk, dan keluhan customer',
            ],
            'Driver & Kurir Lapangan' => [
                'division'      => 'OPER',
                'is_supervisor' => false,
                'description'   => 'Pengemudi dinas kantor dan ekspedisi dokumen lapangan',
            ],
            // Sales & Marketing
            'Sales Supervisor' => [
                'division'      => 'SALE',
                'is_supervisor' => true,
                'description'   => 'Supervisi target tim sales cabang dan persetujuan lembur',
            ],
            'Senior Account Executive' => [
                'division'      => 'SALE',
                'is_supervisor' => false,
                'description'   => 'Pengelolaan portofolio klien korporat dan target penjualan',
            ],
            'Sales Representative' => [
                'division'      => 'SALE',
                'is_supervisor' => false,
                'description'   => 'Tenaga penjual langsung dan prospek customer',
            ],
            'Digital Marketing Specialist' => [
                'division'      => 'MARK',
                'is_supervisor' => false,
                'description'   => 'Pemasaran digital, promosi media sosial, dan event cabang',
            ],
            // Logistics & Warehouse
            'Logistics Supervisor' => [
                'division'      => 'LOGI',
                'is_supervisor' => true,
                'description'   => 'Supervisi gudang cabang, stok barang, dan pengiriman',
            ],
            'Inventory Control & Checker' => [
                'division'      => 'LOGI',
                'is_supervisor' => false,
                'description'   => 'Pemeriksa keluar-masuk barang dan audit stok opname',
            ],
            'Staff Gudang & Ekspedisi' => [
                'division'      => 'LOGI',
                'is_supervisor' => false,
                'description'   => 'Penataan gudang, loading muatan barang, dan ekspedisi',
            ],
            // Finance & Accounting
            'Finance & Accounting Supervisor' => [
                'division'      => 'FINA',
                'is_supervisor' => true,
                'description'   => 'Otorisator keuangan cabang dan approval reimbursement',
            ],
            'Senior Accountant' => [
                'division'      => 'FINA',
                'is_supervisor' => false,
                'description'   => 'Penyusunan pembukuan kas cabang dan rekonsiliasi',
            ],
            'Kasir & Teller Cabang' => [
                'division'      => 'FINA',
                'is_supervisor' => false,
                'description'   => 'Penerimaan pembayaran kas dan transaksi kasir harian',
            ],
            'Staff Finance & Payroll' => [
                'division'      => 'FINA',
                'is_supervisor' => false,
                'description'   => 'Verifikasi struk pengeluaran dan payroll staf cabang',
            ],
            // HR & GA
            'HR & GA Supervisor' => [
                'division'      => 'HRGA',
                'is_supervisor' => true,
                'description'   => 'Pengawasan absensi, cuti, hubungan kerja, dan umum cabang',
            ],
            'Staff Personalia & Absensi' => [
                'division'      => 'HRGA',
                'is_supervisor' => false,
                'description'   => 'Administrasi presensi, klaim cuti, dan berkas karyawan',
            ],
            'Staff Administrasi Umum' => [
                'division'      => 'HRGA',
                'is_supervisor' => false,
                'description'   => 'Pengadaan ATK, fasilitas kantor, dan surat-menyurat',
            ],
            // IT Support
            'IT Supervisor' => [
                'division'      => 'IT',
                'is_supervisor' => true,
                'description'   => 'Pengawas sistem IT, jaringan lokal cabang, dan hardware',
            ],
            'Staff IT Support' => [
                'division'      => 'IT',
                'is_supervisor' => false,
                'description'   => 'Helpdesk teknis hardware, printer, dan konektivitas user',
            ],
        ];

        $positions = [];
        foreach ($positionsData as $name => $pData) {
            $divId = $pData['division'] ? $divisions[$pData['division']]->id : null;
            $pos = Position::firstOrCreate(
                ['company_id' => $company->id, 'name' => $name],
                [
                    'division_id'   => $divId,
                    'is_supervisor' => $pData['is_supervisor'],
                    'description'   => $pData['description'],
                    'is_active'     => true,
                ]
            );
            $positions[$name] = $pos;
        }

        // ─── 4. Roles Map ───
        $roleSuperAdmin   = Role::where('slug', 'super_admin')->first();
        $roleAdmin        = Role::where('slug', 'admin')->first();
        $roleFinance      = Role::where('slug', 'finance')->first();
        $roleHrd          = Role::where('slug', 'hrd')->first();
        $roleEmployee     = Role::where('slug', 'employee')->first();
        $roleKepalaCabang = Role::where('slug', 'kepala_cabang')->first() ?: Role::where('name', 'like', '%kepala cabang%')->first();

        // Hubungkan role kepala cabang ke cabang ini di role_branches
        if ($roleKepalaCabang) {
            DB::table('role_branches')->updateOrInsert(
                [
                    'role_id'               => $roleKepalaCabang->id,
                    'attendance_setting_id' => $branch->id,
                ],
                [
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }

        // Cari General Manager atau Super Admin untuk atasan Kepala Cabang
        $topBoss = User::whereIn('role', ['super_admin', 'admin'])->orderBy('id')->first();

        // ─── 5. Dataset 50 Karyawan Cabang Surabaya ───
        $employees = [
            // ── A. Pimpinan Cabang (1 Orang) ──
            [
                'code'          => 'SBY-001',
                'name'          => 'Bambang Soediro',
                'email'         => 'bambang.soediro@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1980-04-12',
                'position'      => 'Branch Manager',
                'division'      => null,
                'role_slug'     => $roleKepalaCabang ? $roleKepalaCabang->slug : 'admin',
                'role_id'       => $roleKepalaCabang?->id,
                'manager_code'  => null,
                'fallback_mgr'  => $topBoss?->id,
                'joined_date'   => '2021-03-01',
                'emp_type'      => 'PKWTT',
                'claim_limit'   => 20000000,
                'address'       => 'Jl. Raya Darmo No. 82, Wonokromo, Surabaya',
                'postal_code'   => '60241',
                'bank_name'     => 'BCA',
                'bank_acc'      => '0188921001',
            ],

            // ── B. Departemen Operasional (14 Orang: 1 SPV, 1 Lead, 1 Senior, 5 Staff, 3 CS, 3 Driver) ──
            [
                'code'          => 'SBY-002',
                'name'          => 'Eko Prasetyo',
                'email'         => 'eko.prasetyo@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1987-08-20',
                'position'      => 'Operational Supervisor',
                'division'      => 'OPER',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-001',
                'joined_date'   => '2021-06-15',
                'emp_type'      => 'PKWTT',
                'claim_limit'   => 10000000,
                'address'       => 'Jl. Kertajaya Indah No. 45, Manyar Sabrangan, Surabaya',
                'postal_code'   => '60116',
                'bank_name'     => 'Mandiri',
                'bank_acc'      => '1420018820021',
            ],
            [
                'code'          => 'SBY-003',
                'name'          => 'Rahmat Hidayat',
                'email'         => 'rahmat.hidayat@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Sidoarjo',
                'birth_date'    => '1990-11-05',
                'position'      => 'Field Operations Lead',
                'division'      => 'OPER',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-002',
                'joined_date'   => '2022-01-10',
                'emp_type'      => 'PKWTT',
                'claim_limit'   => 7000000,
                'address'       => 'Jl. Pahlawan No. 12, Waru, Sidoarjo',
                'postal_code'   => '61256',
                'bank_name'     => 'BCA',
                'bank_acc'      => '0188921003',
            ],
            [
                'code'          => 'SBY-004',
                'name'          => 'Tri Wahyuni',
                'email'         => 'tri.wahyuni@majubersama.co.id',
                'gender'        => 'Perempuan',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1992-03-14',
                'position'      => 'Senior Staff Operasional',
                'division'      => 'OPER',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-002',
                'joined_date'   => '2022-02-01',
                'emp_type'      => 'PKWTT',
                'claim_limit'   => 6000000,
                'address'       => 'Jl. Kutai No. 28, Sawahan, Surabaya',
                'postal_code'   => '60241',
                'bank_name'     => 'BNI',
                'bank_acc'      => '0238910004',
            ],
            [
                'code'          => 'SBY-005',
                'name'          => 'Bayu Anggoro',
                'email'         => 'bayu.anggoro@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Gresik',
                'birth_date'    => '1995-05-19',
                'position'      => 'Staff Operasional',
                'division'      => 'OPER',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-002',
                'joined_date'   => '2023-03-01',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 5000000,
                'address'       => 'Jl. Veteran No. 67, Kebomas, Gresik',
                'postal_code'   => '61122',
                'bank_name'     => 'BRI',
                'bank_acc'      => '0019820005',
            ],
            [
                'code'          => 'SBY-006',
                'name'          => 'Dian Safitri',
                'email'         => 'dian.safitri@majubersama.co.id',
                'gender'        => 'Perempuan',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1996-09-22',
                'position'      => 'Staff Operasional',
                'division'      => 'OPER',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-002',
                'joined_date'   => '2023-04-15',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 5000000,
                'address'       => 'Jl. Rungkut Asri Timur No. 19, Rungkut, Surabaya',
                'postal_code'   => '60293',
                'bank_name'     => 'BCA',
                'bank_acc'      => '0188921006',
            ],
            [
                'code'          => 'SBY-007',
                'name'          => 'Fajar Nugroho',
                'email'         => 'fajar.nugroho@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Mojokerto',
                'birth_date'    => '1994-07-30',
                'position'      => 'Staff Operasional',
                'division'      => 'OPER',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-002',
                'joined_date'   => '2023-06-01',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 5000000,
                'address'       => 'Jl. Pahlawan No. 40, Magersari, Mojokerto',
                'postal_code'   => '61318',
                'bank_name'     => 'Mandiri',
                'bank_acc'      => '1420018820007',
            ],
            [
                'code'          => 'SBY-008',
                'name'          => 'Indra Lesmana',
                'email'         => 'indra.lesmana@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1997-01-18',
                'position'      => 'Staff Operasional',
                'division'      => 'OPER',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-002',
                'joined_date'   => '2024-01-15',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 5000000,
                'address'       => 'Jl. Menur Pumpungan No. 33, Sukolilo, Surabaya',
                'postal_code'   => '60118',
                'bank_name'     => 'BCA',
                'bank_acc'      => '0188921008',
            ],
            [
                'code'          => 'SBY-009',
                'name'          => 'Mega Utami',
                'email'         => 'mega.utami@majubersama.co.id',
                'gender'        => 'Perempuan',
                'birth_place'   => 'Malang',
                'birth_date'    => '1998-10-12',
                'position'      => 'Staff Operasional',
                'division'      => 'OPER',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-002',
                'joined_date'   => '2024-03-01',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 5000000,
                'address'       => 'Jl. Semolowaru Elok No. 8, Sukolilo, Surabaya',
                'postal_code'   => '60119',
                'bank_name'     => 'BNI',
                'bank_acc'      => '0238910009',
            ],
            [
                'code'          => 'SBY-010',
                'name'          => 'Putri Anggraini',
                'email'         => 'putri.anggraini@majubersama.co.id',
                'gender'        => 'Perempuan',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1999-04-08',
                'position'      => 'Customer Service & Resepsionis',
                'division'      => 'OPER',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-002',
                'joined_date'   => '2023-08-01',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 4000000,
                'address'       => 'Jl. Kusuma Bangsa No. 25, Genteng, Surabaya',
                'postal_code'   => '60272',
                'bank_name'     => 'BCA',
                'bank_acc'      => '0188921010',
            ],
            [
                'code'          => 'SBY-011',
                'name'          => 'Lestari Wulandari',
                'email'         => 'lestari.wulandari@majubersama.co.id',
                'gender'        => 'Perempuan',
                'birth_place'   => 'Sidoarjo',
                'birth_date'    => '2000-02-17',
                'position'      => 'Customer Service & Resepsionis',
                'division'      => 'OPER',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-002',
                'joined_date'   => '2024-02-01',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 4000000,
                'address'       => 'Jl. Diponegoro No. 88, Sedati, Sidoarjo',
                'postal_code'   => '61253',
                'bank_name'     => 'BRI',
                'bank_acc'      => '0019820011',
            ],
            [
                'code'          => 'SBY-012',
                'name'          => 'Nabila Syahrani',
                'email'         => 'nabila.syahrani@majubersama.co.id',
                'gender'        => 'Perempuan',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '2001-06-25',
                'position'      => 'Customer Service & Resepsionis',
                'division'      => 'OPER',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-002',
                'joined_date'   => '2024-05-01',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 4000000,
                'address'       => 'Jl. Ngagel Jaya Selatan No. 14, Gubeng, Surabaya',
                'postal_code'   => '60283',
                'bank_name'     => 'BCA',
                'bank_acc'      => '0188921012',
            ],
            [
                'code'          => 'SBY-013',
                'name'          => 'Agus Santoso',
                'email'         => 'agus.santoso@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1989-12-10',
                'position'      => 'Driver & Kurir Lapangan',
                'division'      => 'OPER',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-002',
                'joined_date'   => '2022-05-01',
                'emp_type'      => 'PKWTT',
                'claim_limit'   => 4500000,
                'address'       => 'Jl. Joyoboyo No. 5, Wonokromo, Surabaya',
                'postal_code'   => '60242',
                'bank_name'     => 'Mandiri',
                'bank_acc'      => '1420018820013',
            ],
            [
                'code'          => 'SBY-014',
                'name'          => 'Slamet Riyadi',
                'email'         => 'slamet.riyadi@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Gresik',
                'birth_date'    => '1991-08-04',
                'position'      => 'Driver & Kurir Lapangan',
                'division'      => 'OPER',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-002',
                'joined_date'   => '2022-09-15',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 4500000,
                'address'       => 'Jl. Panglima Sudirman No. 71, Gresik',
                'postal_code'   => '61111',
                'bank_name'     => 'BRI',
                'bank_acc'      => '0019820014',
            ],
            [
                'code'          => 'SBY-015',
                'name'          => 'Joko Purnomo',
                'email'         => 'joko.purnomo@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Sidoarjo',
                'birth_date'    => '1993-04-18',
                'position'      => 'Driver & Kurir Lapangan',
                'division'      => 'OPER',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-002',
                'joined_date'   => '2023-01-10',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 4500000,
                'address'       => 'Jl. Raya Tropodo No. 29, Waru, Sidoarjo',
                'postal_code'   => '61256',
                'bank_name'     => 'BCA',
                'bank_acc'      => '0188921015',
            ],

            // ── C. Departemen Penjualan & Pemasaran (14 Orang: 1 SPV, 3 Senior AE, 8 Sales Rep, 2 Marketing) ──
            [
                'code'          => 'SBY-016',
                'name'          => 'Arif Budiman',
                'email'         => 'arif.budiman@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1986-02-14',
                'position'      => 'Sales Supervisor',
                'division'      => 'SALE',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-001',
                'joined_date'   => '2021-04-01',
                'emp_type'      => 'PKWTT',
                'claim_limit'   => 12000000,
                'address'       => 'Jl. Mayjen Sungkono No. 102, Dukuh Pakis, Surabaya',
                'postal_code'   => '60225',
                'bank_name'     => 'BCA',
                'bank_acc'      => '0188921016',
            ],
            [
                'code'          => 'SBY-017',
                'name'          => 'Dimas Pratama',
                'email'         => 'dimas.pratama@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Malang',
                'birth_date'    => '1991-06-20',
                'position'      => 'Senior Account Executive',
                'division'      => 'SALE',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-016',
                'joined_date'   => '2022-03-01',
                'emp_type'      => 'PKWTT',
                'claim_limit'   => 8000000,
                'address'       => 'Jl. Dharmahusada Indah No. 55, Mulyorejo, Surabaya',
                'postal_code'   => '60115',
                'bank_name'     => 'Mandiri',
                'bank_acc'      => '1420018820017',
            ],
            [
                'code'          => 'SBY-018',
                'name'          => 'Citra Dewi',
                'email'         => 'citra.dewi@majubersama.co.id',
                'gender'        => 'Perempuan',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1992-09-09',
                'position'      => 'Senior Account Executive',
                'division'      => 'SALE',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-016',
                'joined_date'   => '2022-07-15',
                'emp_type'      => 'PKWTT',
                'claim_limit'   => 8000000,
                'address'       => 'Jl. Manyar Kertoarjo No. 21, Mulyorejo, Surabaya',
                'postal_code'   => '60116',
                'bank_name'     => 'BCA',
                'bank_acc'      => '0188921018',
            ],
            [
                'code'          => 'SBY-019',
                'name'          => 'Reza Fahlevi',
                'email'         => 'reza.fahlevi@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1993-11-28',
                'position'      => 'Senior Account Executive',
                'division'      => 'SALE',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-016',
                'joined_date'   => '2022-10-01',
                'emp_type'      => 'PKWTT',
                'claim_limit'   => 8000000,
                'address'       => 'Jl. HR Muhammad No. 89, Sukomanunggal, Surabaya',
                'postal_code'   => '60189',
                'bank_name'     => 'BNI',
                'bank_acc'      => '0238910019',
            ],
            [
                'code'          => 'SBY-020',
                'name'          => 'Aditya Wardhana',
                'email'         => 'aditya.wardhana@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Sidoarjo',
                'birth_date'    => '1995-01-14',
                'position'      => 'Sales Representative',
                'division'      => 'SALE',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-016',
                'joined_date'   => '2023-02-01',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 6000000,
                'address'       => 'Jl. Gajah Mada No. 15, Sidoarjo',
                'postal_code'   => '61212',
                'bank_name'     => 'BCA',
                'bank_acc'      => '0188921020',
            ],
            [
                'code'          => 'SBY-021',
                'name'          => 'Bella Permata',
                'email'         => 'bella.permata@majubersama.co.id',
                'gender'        => 'Perempuan',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1996-03-25',
                'position'      => 'Sales Representative',
                'division'      => 'SALE',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-016',
                'joined_date'   => '2023-04-01',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 6000000,
                'address'       => 'Jl. Gubeng Kertajaya VII No. 11, Gubeng, Surabaya',
                'postal_code'   => '60281',
                'bank_name'     => 'Mandiri',
                'bank_acc'      => '1420018820021',
            ],
            [
                'code'          => 'SBY-022',
                'name'          => 'Candra Wijaya',
                'email'         => 'candra.wijaya@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Pasuruan',
                'birth_date'    => '1995-08-11',
                'position'      => 'Sales Representative',
                'division'      => 'SALE',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-016',
                'joined_date'   => '2023-05-15',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 6000000,
                'address'       => 'Jl. Sukarno Hatta No. 42, Gadingrejo, Pasuruan',
                'postal_code'   => '67134',
                'bank_name'     => 'BRI',
                'bank_acc'      => '0019820022',
            ],
            [
                'code'          => 'SBY-023',
                'name'          => 'Dina Mariana',
                'email'         => 'dina.mariana@majubersama.co.id',
                'gender'        => 'Perempuan',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1997-12-04',
                'position'      => 'Sales Representative',
                'division'      => 'SALE',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-016',
                'joined_date'   => '2023-09-01',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 6000000,
                'address'       => 'Jl. Karang Menjangan No. 36, Gubeng, Surabaya',
                'postal_code'   => '60285',
                'bank_name'     => 'BCA',
                'bank_acc'      => '0188921023',
            ],
            [
                'code'          => 'SBY-024',
                'name'          => 'Erick Setiawan',
                'email'         => 'erick.setiawan@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1996-05-16',
                'position'      => 'Sales Representative',
                'division'      => 'SALE',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-016',
                'joined_date'   => '2023-11-01',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 6000000,
                'address'       => 'Jl. Jemursari Barat No. 20, Wonocolo, Surabaya',
                'postal_code'   => '60237',
                'bank_name'     => 'BNI',
                'bank_acc'      => '0238910024',
            ],
            [
                'code'          => 'SBY-025',
                'name'          => 'Febri Ardiansyah',
                'email'         => 'febri.ardiansyah@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Gresik',
                'birth_date'    => '1998-02-28',
                'position'      => 'Sales Representative',
                'division'      => 'SALE',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-016',
                'joined_date'   => '2024-01-08',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 6000000,
                'address'       => 'Jl. Dr. Wahidin Sudirohusodo No. 90, Kebomas, Gresik',
                'postal_code'   => '61121',
                'bank_name'     => 'BCA',
                'bank_acc'      => '0188921025',
            ],
            [
                'code'          => 'SBY-026',
                'name'          => 'Gita Maharani',
                'email'         => 'gita.maharani@majubersama.co.id',
                'gender'        => 'Perempuan',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1999-07-15',
                'position'      => 'Sales Representative',
                'division'      => 'SALE',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-016',
                'joined_date'   => '2024-03-01',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 6000000,
                'address'       => 'Jl. Ngagel Tama No. 18, Wonokromo, Surabaya',
                'postal_code'   => '60283',
                'bank_name'     => 'Mandiri',
                'bank_acc'      => '1420018820026',
            ],
            [
                'code'          => 'SBY-027',
                'name'          => 'Hadi Susilo',
                'email'         => 'hadi.susilo@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1997-10-30',
                'position'      => 'Sales Representative',
                'division'      => 'SALE',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-016',
                'joined_date'   => '2024-04-15',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 6000000,
                'address'       => 'Jl. Bratang Binangun No. 49, Gubeng, Surabaya',
                'postal_code'   => '60284',
                'bank_name'     => 'BRI',
                'bank_acc'      => '0019820027',
            ],
            [
                'code'          => 'SBY-028',
                'name'          => 'Intan Nuraini',
                'email'         => 'intan.nuraini@majubersama.co.id',
                'gender'        => 'Perempuan',
                'birth_place'   => 'Malang',
                'birth_date'    => '1996-01-24',
                'position'      => 'Digital Marketing Specialist',
                'division'      => 'MARK',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-016',
                'joined_date'   => '2023-05-01',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 6000000,
                'address'       => 'Jl. Bendul Merisi Permai No. 12, Wonokromo, Surabaya',
                'postal_code'   => '60239',
                'bank_name'     => 'BCA',
                'bank_acc'      => '0188921028',
            ],
            [
                'code'          => 'SBY-029',
                'name'          => 'Kevin Alamsyah',
                'email'         => 'kevin.alamsyah@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1998-04-19',
                'position'      => 'Digital Marketing Specialist',
                'division'      => 'MARK',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-016',
                'joined_date'   => '2024-02-15',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 6000000,
                'address'       => 'Jl. Klampis Jaya No. 70, Sukolilo, Surabaya',
                'postal_code'   => '60117',
                'bank_name'     => 'BNI',
                'bank_acc'      => '0238910029',
            ],

            // ── D. Departemen Gudang & Logistik (10 Orang: 1 SPV, 2 Checker, 7 Staf Gudang) ──
            [
                'code'          => 'SBY-030',
                'name'          => 'Wahyu Hidayat',
                'email'         => 'wahyu.hidayat@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Sidoarjo',
                'birth_date'    => '1985-09-17',
                'position'      => 'Logistics Supervisor',
                'division'      => 'LOGI',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-001',
                'joined_date'   => '2021-05-01',
                'emp_type'      => 'PKWTT',
                'claim_limit'   => 10000000,
                'address'       => 'Jl. Raya Rungkut Industri No. 10, Tenggilis Mejoyo, Surabaya',
                'postal_code'   => '60292',
                'bank_name'     => 'BCA',
                'bank_acc'      => '0188921030',
            ],
            [
                'code'          => 'SBY-031',
                'name'          => 'Lukman Hakim',
                'email'         => 'lukman.hakim@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1991-03-29',
                'position'      => 'Inventory Control & Checker',
                'division'      => 'LOGI',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-030',
                'joined_date'   => '2022-04-01',
                'emp_type'      => 'PKWTT',
                'claim_limit'   => 6000000,
                'address'       => 'Jl. Margomulyo No. 44, Asemrowo, Surabaya',
                'postal_code'   => '60183',
                'bank_name'     => 'Mandiri',
                'bank_acc'      => '1420018820031',
            ],
            [
                'code'          => 'SBY-032',
                'name'          => 'Miftahul Huda',
                'email'         => 'miftahul.huda@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Gresik',
                'birth_date'    => '1993-07-08',
                'position'      => 'Inventory Control & Checker',
                'division'      => 'LOGI',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-030',
                'joined_date'   => '2022-08-15',
                'emp_type'      => 'PKWTT',
                'claim_limit'   => 6000000,
                'address'       => 'Jl. Raya Manyar No. 23, Manyar, Gresik',
                'postal_code'   => '61151',
                'bank_name'     => 'BCA',
                'bank_acc'      => '0188921032',
            ],
            [
                'code'          => 'SBY-033',
                'name'          => 'Nanang Kosim',
                'email'         => 'nanang.kosim@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1994-11-12',
                'position'      => 'Staff Gudang & Ekspedisi',
                'division'      => 'LOGI',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-030',
                'joined_date'   => '2023-01-10',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 5000000,
                'address'       => 'Jl. Tanjungsari No. 51, Sukomanunggal, Surabaya',
                'postal_code'   => '60187',
                'bank_name'     => 'BRI',
                'bank_acc'      => '0019820033',
            ],
            [
                'code'          => 'SBY-034',
                'name'          => 'Oki Firmansyah',
                'email'         => 'oki.firmansyah@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Sidoarjo',
                'birth_date'    => '1995-02-18',
                'position'      => 'Staff Gudang & Ekspedisi',
                'division'      => 'LOGI',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-030',
                'joined_date'   => '2023-03-15',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 5000000,
                'address'       => 'Jl. Berbek Industri No. 7, Waru, Sidoarjo',
                'postal_code'   => '61256',
                'bank_name'     => 'BNI',
                'bank_acc'      => '0238910034',
            ],
            [
                'code'          => 'SBY-035',
                'name'          => 'Pandu Wicaksono',
                'email'         => 'pandu.wicaksono@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1996-06-21',
                'position'      => 'Staff Gudang & Ekspedisi',
                'division'      => 'LOGI',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-030',
                'joined_date'   => '2023-06-01',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 5000000,
                'address'       => 'Jl. Kalianak Barat No. 80, Asemrowo, Surabaya',
                'postal_code'   => '60183',
                'bank_name'     => 'BCA',
                'bank_acc'      => '0188921035',
            ],
            [
                'code'          => 'SBY-036',
                'name'          => 'Rico Maulana',
                'email'         => 'rico.maulana@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Mojokerto',
                'birth_date'    => '1997-09-03',
                'position'      => 'Staff Gudang & Ekspedisi',
                'division'      => 'LOGI',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-030',
                'joined_date'   => '2023-08-15',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 5000000,
                'address'       => 'Jl. Mastrip No. 102, Karang Pilang, Surabaya',
                'postal_code'   => '60221',
                'bank_name'     => 'Mandiri',
                'bank_acc'      => '1420018820036',
            ],
            [
                'code'          => 'SBY-037',
                'name'          => 'Surya Saputra',
                'email'         => 'surya.saputra@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1998-01-11',
                'position'      => 'Staff Gudang & Ekspedisi',
                'division'      => 'LOGI',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-030',
                'joined_date'   => '2024-01-10',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 5000000,
                'address'       => 'Jl. Kedung Baruk No. 25, Rungkut, Surabaya',
                'postal_code'   => '60298',
                'bank_name'     => 'BRI',
                'bank_acc'      => '0019820037',
            ],
            [
                'code'          => 'SBY-038',
                'name'          => 'Taufik Ismail',
                'email'         => 'taufik.ismail@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Sidoarjo',
                'birth_date'    => '1999-05-04',
                'position'      => 'Staff Gudang & Ekspedisi',
                'division'      => 'LOGI',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-030',
                'joined_date'   => '2024-03-01',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 5000000,
                'address'       => 'Jl. Tambak Sumur No. 16, Waru, Sidoarjo',
                'postal_code'   => '61256',
                'bank_name'     => 'BCA',
                'bank_acc'      => '0188921038',
            ],
            [
                'code'          => 'SBY-039',
                'name'          => 'Untung Suropati',
                'email'         => 'untung.suropati@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1997-12-14',
                'position'      => 'Staff Gudang & Ekspedisi',
                'division'      => 'LOGI',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-030',
                'joined_date'   => '2024-04-15',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 5000000,
                'address'       => 'Jl. Tambak Oso Wilangun No. 63, Benowo, Surabaya',
                'postal_code'   => '60191',
                'bank_name'     => 'BNI',
                'bank_acc'      => '0238910039',
            ],

            // ── E. Departemen Keuangan & Kasir (6 Orang: 1 SPV, 1 Senior, 2 Kasir, 2 Staf Klaim/Payroll) ──
            [
                'code'          => 'SBY-040',
                'name'          => 'Vina Rosalina',
                'email'         => 'vina.rosalina@majubersama.co.id',
                'gender'        => 'Perempuan',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1988-10-09',
                'position'      => 'Finance & Accounting Supervisor',
                'division'      => 'FINA',
                'role_slug'     => 'finance',
                'role_id'       => $roleFinance?->id,
                'manager_code'  => 'SBY-001',
                'joined_date'   => '2021-04-15',
                'emp_type'      => 'PKWTT',
                'claim_limit'   => 15000000,
                'address'       => 'Jl. Pregolan No. 8, Tegalsari, Surabaya',
                'postal_code'   => '60262',
                'bank_name'     => 'BCA',
                'bank_acc'      => '0188921040',
            ],
            [
                'code'          => 'SBY-041',
                'name'          => 'Wawan Hendrawan',
                'email'         => 'wawan.hendrawan@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Malang',
                'birth_date'    => '1990-07-23',
                'position'      => 'Senior Accountant',
                'division'      => 'FINA',
                'role_slug'     => 'finance',
                'role_id'       => $roleFinance?->id,
                'manager_code'  => 'SBY-040',
                'joined_date'   => '2022-02-01',
                'emp_type'      => 'PKWTT',
                'claim_limit'   => 8000000,
                'address'       => 'Jl. Urip Sumoharjo No. 40, Tegalsari, Surabaya',
                'postal_code'   => '60265',
                'bank_name'     => 'Mandiri',
                'bank_acc'      => '1420018820041',
            ],
            [
                'code'          => 'SBY-042',
                'name'          => 'Yeny Marlina',
                'email'         => 'yeny.marlina@majubersama.co.id',
                'gender'        => 'Perempuan',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1995-04-16',
                'position'      => 'Kasir & Teller Cabang',
                'division'      => 'FINA',
                'role_slug'     => 'finance',
                'role_id'       => $roleFinance?->id,
                'manager_code'  => 'SBY-040',
                'joined_date'   => '2023-01-15',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 6000000,
                'address'       => 'Jl. Embong Ploso No. 15, Genteng, Surabaya',
                'postal_code'   => '60271',
                'bank_name'     => 'BCA',
                'bank_acc'      => '0188921042',
            ],
            [
                'code'          => 'SBY-043',
                'name'          => 'Zainal Abidin',
                'email'         => 'zainal.abidin@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Gresik',
                'birth_date'    => '1996-08-30',
                'position'      => 'Kasir & Teller Cabang',
                'division'      => 'FINA',
                'role_slug'     => 'finance',
                'role_id'       => $roleFinance?->id,
                'manager_code'  => 'SBY-040',
                'joined_date'   => '2023-05-01',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 6000000,
                'address'       => 'Jl. RA Kartini No. 50, Kebomas, Gresik',
                'postal_code'   => '61122',
                'bank_name'     => 'BRI',
                'bank_acc'      => '0019820043',
            ],
            [
                'code'          => 'SBY-044',
                'name'          => 'Anisa Rahmawati',
                'email'         => 'anisa.rahmawati@majubersama.co.id',
                'gender'        => 'Perempuan',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1997-03-11',
                'position'      => 'Staff Finance & Payroll',
                'division'      => 'FINA',
                'role_slug'     => 'finance',
                'role_id'       => $roleFinance?->id,
                'manager_code'  => 'SBY-040',
                'joined_date'   => '2023-09-15',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 6000000,
                'address'       => 'Jl. Dinoyo No. 82, Tegalsari, Surabaya',
                'postal_code'   => '60265',
                'bank_name'     => 'BNI',
                'bank_acc'      => '0238910044',
            ],
            [
                'code'          => 'SBY-045',
                'name'          => 'Bagus Prakoso',
                'email'         => 'bagus.prakoso@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Sidoarjo',
                'birth_date'    => '1998-11-20',
                'position'      => 'Staff Finance & Payroll',
                'division'      => 'FINA',
                'role_slug'     => 'finance',
                'role_id'       => $roleFinance?->id,
                'manager_code'  => 'SBY-040',
                'joined_date'   => '2024-02-01',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 6000000,
                'address'       => 'Jl. Pahlawan No. 78, Sidokumpul, Sidoarjo',
                'postal_code'   => '61212',
                'bank_name'     => 'BCA',
                'bank_acc'      => '0188921045',
            ],

            // ── F. Departemen HR & General Affairs (3 Orang: 1 SPV, 1 Staff Personalia, 1 Staff Umum) ──
            [
                'code'          => 'SBY-046',
                'name'          => 'Chandra Kusuma',
                'email'         => 'chandra.kusuma@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1987-12-05',
                'position'      => 'HR & GA Supervisor',
                'division'      => 'HRGA',
                'role_slug'     => 'hrd',
                'role_id'       => $roleHrd?->id,
                'manager_code'  => 'SBY-001',
                'joined_date'   => '2021-07-01',
                'emp_type'      => 'PKWTT',
                'claim_limit'   => 10000000,
                'address'       => 'Jl. Ciliwung No. 24, Wonokromo, Surabaya',
                'postal_code'   => '60241',
                'bank_name'     => 'BCA',
                'bank_acc'      => '0188921046',
            ],
            [
                'code'          => 'SBY-047',
                'name'          => 'Dewi Sartika',
                'email'         => 'dewi.sartika@majubersama.co.id',
                'gender'        => 'Perempuan',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1995-09-18',
                'position'      => 'Staff Personalia & Absensi',
                'division'      => 'HRGA',
                'role_slug'     => 'hrd',
                'role_id'       => $roleHrd?->id,
                'manager_code'  => 'SBY-046',
                'joined_date'   => '2023-03-01',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 5000000,
                'address'       => 'Jl. Marmoyo No. 9, Wonokromo, Surabaya',
                'postal_code'   => '60241',
                'bank_name'     => 'Mandiri',
                'bank_acc'      => '1420018820047',
            ],
            [
                'code'          => 'SBY-048',
                'name'          => 'Erwin Gutawa',
                'email'         => 'erwin.gutawa@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Sidoarjo',
                'birth_date'    => '1996-01-30',
                'position'      => 'Staff Administrasi Umum',
                'division'      => 'HRGA',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-046',
                'joined_date'   => '2023-07-15',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 5000000,
                'address'       => 'Jl. Raya Wadungasri No. 14, Waru, Sidoarjo',
                'postal_code'   => '61256',
                'bank_name'     => 'BRI',
                'bank_acc'      => '0019820048',
            ],

            // ── G. Departemen IT Support (2 Orang: 1 Lead SPV, 1 Staff IT Support) ──
            [
                'code'          => 'SBY-049',
                'name'          => 'Farhan Alfarizi',
                'email'         => 'farhan.alfarizi@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1992-05-27',
                'position'      => 'IT Supervisor',
                'division'      => 'IT',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-001',
                'joined_date'   => '2022-01-15',
                'emp_type'      => 'PKWTT',
                'claim_limit'   => 9000000,
                'address'       => 'Jl. Ketintang Baru No. 30, Gayungan, Surabaya',
                'postal_code'   => '60231',
                'bank_name'     => 'BCA',
                'bank_acc'      => '0188921049',
            ],
            [
                'code'          => 'SBY-050',
                'name'          => 'Gilang Ramadhan',
                'email'         => 'gilang.ramadhan@majubersama.co.id',
                'gender'        => 'Laki-laki',
                'birth_place'   => 'Surabaya',
                'birth_date'    => '1997-08-14',
                'position'      => 'Staff IT Support',
                'division'      => 'IT',
                'role_slug'     => 'employee',
                'role_id'       => $roleEmployee?->id,
                'manager_code'  => 'SBY-049',
                'joined_date'   => '2023-08-01',
                'emp_type'      => 'PKWT',
                'claim_limit'   => 5000000,
                'address'       => 'Jl. Jetis Kulon No. 17, Wonokromo, Surabaya',
                'postal_code'   => '60243',
                'bank_name'     => 'Mandiri',
                'bank_acc'      => '1420018820050',
            ],
        ];

        $this->command?->info("👥 Menginput 50 Karyawan terstruktur untuk {$branch->office_name}...");

        $createdUsers = [];
        $defaultPassword = Hash::make('password');

        // Tahap 1: Buat / Update seluruh user (tanpa manager_id dahulu untuk menghindari foreign key constraint race)
        foreach ($employees as $idx => $emp) {
            $divId = $emp['division'] ? $divisions[$emp['division']]->id : null;
            $posId = $positions[$emp['position']]->id;
            $nikKtp = '3578' . str_pad((string) ($idx + 1), 2, '0', STR_PAD_LEFT) . date('dmy', strtotime($emp['birth_date'])) . '0001';

            $user = User::updateOrCreate(
                [
                    'email' => $emp['email'],
                ],
                [
                    'company_id'              => $company->id,
                    'name'                    => $emp['name'],
                    'password'                => $defaultPassword,
                    'employee_code'           => $emp['code'],
                    'identity_number'         => $nikKtp,
                    'phone'                   => '08' . rand(11, 23) . rand(1000, 9999) . str_pad((string) ($idx + 1), 4, '0', STR_PAD_LEFT),
                    'gender'                  => $emp['gender'],
                    'birth_place'             => $emp['birth_place'],
                    'birth_date'              => $emp['birth_date'],
                    'attendance_setting_id'   => $branch->id,
                    'division_id'             => $divId,
                    'department'              => $emp['division'] ? $divisions[$emp['division']]->name : null,
                    'position_id'             => $posId,
                    'role'                    => $emp['role_slug'],
                    'role_id'                 => $emp['role_id'],
                    'joined_date'             => $emp['joined_date'],
                    'employment_type'         => $emp['emp_type'],
                    'monthly_claim_limit'     => $emp['claim_limit'],
                    'is_active'               => true,
                    'attendance_enabled'      => true,
                    'overtime_enabled'        => true,
                    'wfh_enabled'             => true,
                    'radius_enabled'          => true,
                    'dinas_luar_enabled'      => true,
                    'allow_attendance'        => true,
                    'allow_wfh'               => true,
                    'allow_radius'            => true,
                    'ktp_address'             => $emp['address'],
                    'ktp_city'                => 'Kota Surabaya',
                    'ktp_province'            => 'Jawa Timur',
                    'ktp_postal_code'         => $emp['postal_code'],
                    'domicile_address'        => $emp['address'],
                    'is_domicile_same_as_ktp' => true,
                    'religion'                => ($idx % 5 === 0 ? 'Kristen' : ($idx % 7 === 0 ? 'Katolik' : 'Islam')),
                    'marital_status'          => (strtotime($emp['birth_date']) < strtotime('1995-01-01') ? 'married' : 'single'),
                    'number_of_dependents'    => (strtotime($emp['birth_date']) < strtotime('1995-01-01') ? rand(1, 2) : 0),
                    'blood_type'              => ['A', 'B', 'O', 'AB'][$idx % 4],
                    'medical_conditions'      => 'Sehat jasmani dan rohani',
                    'bank_name'               => $emp['bank_name'],
                    'bank_account_no'         => $emp['bank_acc'],
                    'bank_account_holder'     => $emp['name'],
                ]
            );

            $createdUsers[$emp['code']] = $user;
        }

        // Tahap 2: Sambungkan Hierarki (manager_id) antar atasan dan bawahan
        foreach ($employees as $emp) {
            $user = $createdUsers[$emp['code']] ?? null;
            if (! $user) {
                continue;
            }

            $managerId = null;
            if (! empty($emp['manager_code']) && isset($createdUsers[$emp['manager_code']])) {
                $managerId = $createdUsers[$emp['manager_code']]->id;
            } elseif (isset($emp['fallback_mgr'])) {
                $managerId = $emp['fallback_mgr'];
            }

            $user->update(['manager_id' => $managerId]);
        }

        $this->command?->info("🎉 Sukses membuat 50 karyawan terstruktur untuk Kantor Cabang Surabaya!");
        $this->command?->info("   Email login: <nama>@majubersama.co.id");
        $this->command?->info("   Password semua user: 'password'");
        $this->command?->info("   Kepala Cabang: bambang.soediro@majubersama.co.id (SBY-001)");
    }
}
