<?php

namespace Database\Seeders;

use App\Models\Company;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DummyPersonalDataSeeder extends Seeder
{
    /**
     * Run the database seeds to populate personal & demographic data for existing & test users.
     */
    public function run(): void
    {
        $company = Company::first();
        if (!$company) {
            $company = Company::create([
                'name'      => 'PT Maju Bersama',
                'email'     => 'info@majubersama.co.id',
                'phone'     => '021-5555-1234',
                'address'   => 'Jl. Sudirman No. 10, Jakarta Selatan',
                'is_active' => true,
            ]);
        }

        // 1. Data Dummy Lengkap untuk Pengguna yang Sudah Ada
        $userDataMap = [
            'budi@majubersama.co.id' => [
                'gender'                     => 'Laki-laki',
                'identity_number'            => '3174011506940001',
                'birth_place'                => 'Jakarta',
                'birth_date'                 => '1994-06-15',
                'phone'                      => '081289123401',
                'ktp_address'                => 'Jl. Tebet Barat Dalam VII No. 18, RT 04/RW 02, Tebet Barat, Tebet',
                'ktp_city'                   => 'Jakarta Selatan',
                'ktp_province'               => 'DKI Jakarta',
                'ktp_postal_code'            => '12810',
                'domicile_address'           => 'Jl. Tebet Barat Dalam VII No. 18, RT 04/RW 02, Tebet Barat, Tebet',
                'is_domicile_same_as_ktp'    => true,
                'emergency_contact_name'     => 'Maya Indah',
                'emergency_contact_relation' => 'Pasangan',
                'emergency_contact_phone'    => '081289123499',
                'emergency_contact_address'  => 'Jl. Tebet Barat Dalam VII No. 18, Jakarta Selatan',
                'religion'                   => 'Islam',
                'marital_status'             => 'married',
                'number_of_dependents'       => 1,
                'blood_type'                 => 'O',
                'medical_conditions'         => 'Tidak ada riwayat alergi atau penyakit kronis (Sehat)',
                'bank_name'                  => 'BCA',
                'bank_account_no'            => '7310482910',
                'bank_account_holder'        => 'Budi Wicaksono',
                'employment_type'            => 'PKWTT',
                'joined_date'                => '2023-02-01',
            ],
            'siti@majubersama.co.id' => [
                'gender'                     => 'Perempuan',
                'identity_number'            => '3273016411970002',
                'birth_place'                => 'Bandung',
                'birth_date'                 => '1997-11-24',
                'phone'                      => '081322334402',
                'ktp_address'                => 'Jl. Dago Asri No. 42, RT 02/RW 09, Dago, Coblong',
                'ktp_city'                   => 'Bandung',
                'ktp_province'               => 'Jawa Barat',
                'ktp_postal_code'            => '40135',
                'domicile_address'           => 'Jl. Dr. Saharjo No. 105, RT 01/RW 06, Tebet Barat, Jakarta Selatan',
                'is_domicile_same_as_ktp'    => false,
                'emergency_contact_name'     => 'Ahmad Rahayu',
                'emergency_contact_relation' => 'Orang Tua',
                'emergency_contact_phone'    => '081322334499',
                'emergency_contact_address'  => 'Jl. Dago Asri No. 42, Coblong, Bandung',
                'religion'                   => 'Islam',
                'marital_status'             => 'single',
                'number_of_dependents'       => 0,
                'blood_type'                 => 'A',
                'medical_conditions'         => 'Alergi dingin & debu ringan',
                'bank_name'                  => 'Bank Mandiri',
                'bank_account_no'            => '1370019284710',
                'bank_account_holder'        => 'Siti Rahayu',
                'employment_type'            => 'PKWT',
                'joined_date'                => '2024-01-10',
            ],
            'andi@majubersama.co.id' => [
                'gender'                     => 'Laki-laki',
                'identity_number'            => '3172011803910003',
                'birth_place'                => 'Surabaya',
                'birth_date'                 => '1991-03-18',
                'phone'                      => '081512345603',
                'ktp_address'                => 'Jl. Boulevard Barat Raya Blok LC No. 8, Kelapa Gading Barat',
                'ktp_city'                   => 'Jakarta Utara',
                'ktp_province'               => 'DKI Jakarta',
                'ktp_postal_code'            => '14240',
                'domicile_address'           => 'Jl. Boulevard Barat Raya Blok LC No. 8, Kelapa Gading Barat',
                'is_domicile_same_as_ktp'    => true,
                'emergency_contact_name'     => 'Dian Pratama',
                'emergency_contact_relation' => 'Pasangan',
                'emergency_contact_phone'    => '081512345699',
                'emergency_contact_address'  => 'Jl. Boulevard Barat Raya Blok LC No. 8, Jakarta Utara',
                'religion'                   => 'Islam',
                'marital_status'             => 'married',
                'number_of_dependents'       => 2,
                'blood_type'                 => 'B',
                'medical_conditions'         => 'Minus mata (-2.00 kacamata)',
                'bank_name'                  => 'BCA',
                'bank_account_no'            => '5220819234',
                'bank_account_holder'        => 'Andi Pratama',
                'employment_type'            => 'PKWTT',
                'joined_date'                => '2022-08-15',
            ],
            'rina@majubersama.co.id' => [
                'gender'                     => 'Perempuan',
                'identity_number'            => '3171014809950004',
                'birth_place'                => 'Semarang',
                'birth_date'                 => '1995-09-08',
                'phone'                      => '081298765404',
                'ktp_address'                => 'Jl. Cempaka Putih Tengah No. 25, Cempaka Putih Timur',
                'ktp_city'                   => 'Jakarta Pusat',
                'ktp_province'               => 'DKI Jakarta',
                'ktp_postal_code'            => '10510',
                'domicile_address'           => 'Jl. Cempaka Putih Tengah No. 25, Cempaka Putih Timur',
                'is_domicile_same_as_ktp'    => true,
                'emergency_contact_name'     => 'Bambang Susanti',
                'emergency_contact_relation' => 'Saudara Kandung',
                'emergency_contact_phone'    => '081298765499',
                'emergency_contact_address'  => 'Jl. Cempaka Putih Tengah No. 25, Jakarta Pusat',
                'religion'                   => 'Kristen',
                'marital_status'             => 'single',
                'number_of_dependents'       => 0,
                'blood_type'                 => 'AB',
                'medical_conditions'         => 'Tidak ada riwayat penyakit kronis (Sehat)',
                'bank_name'                  => 'BNI',
                'bank_account_no'            => '0429182736',
                'bank_account_holder'        => 'Rina Susanti',
                'employment_type'            => 'PKWTT',
                'joined_date'                => '2023-05-02',
            ],
            'dewi@majubersama.co.id' => [
                'gender'                     => 'Perempuan',
                'identity_number'            => '3173015412900005',
                'birth_place'                => 'Yogyakarta',
                'birth_date'                 => '1990-12-14',
                'phone'                      => '081823456705',
                'ktp_address'                => 'Jl. Kebon Jeruk Raya No. 33, Kebon Jeruk',
                'ktp_city'                   => 'Jakarta Barat',
                'ktp_province'               => 'DKI Jakarta',
                'ktp_postal_code'            => '11530',
                'domicile_address'           => 'Jl. Kebon Jeruk Raya No. 33, Kebon Jeruk',
                'is_domicile_same_as_ktp'    => true,
                'emergency_contact_name'     => 'Surya Wibawa',
                'emergency_contact_relation' => 'Pasangan',
                'emergency_contact_phone'    => '081823456799',
                'emergency_contact_address'  => 'Jl. Kebon Jeruk Raya No. 33, Jakarta Barat',
                'religion'                   => 'Islam',
                'marital_status'             => 'married',
                'number_of_dependents'       => 2,
                'blood_type'                 => 'O',
                'medical_conditions'         => 'Alergi udang & kepiting',
                'bank_name'                  => 'Bank Mandiri',
                'bank_account_no'            => '1220008492019',
                'bank_account_holder'        => 'Dewi Lestari',
                'employment_type'            => 'PKWTT',
                'joined_date'                => '2021-11-01',
            ],
            'hendra@majubersama.co.id' => [
                'gender'                     => 'Laki-laki',
                'identity_number'            => '3172022207880006',
                'birth_place'                => 'Jakarta',
                'birth_date'                 => '1988-07-22',
                'phone'                      => '081678901206',
                'ktp_address'                => 'Jl. Danau Sunter Utara Blok F No. 12, Sunter Agung',
                'ktp_city'                   => 'Jakarta Utara',
                'ktp_province'               => 'DKI Jakarta',
                'ktp_postal_code'            => '14350',
                'domicile_address'           => 'Jl. Danau Sunter Utara Blok F No. 12, Sunter Agung',
                'is_domicile_same_as_ktp'    => true,
                'emergency_contact_name'     => 'Linda Gunawan',
                'emergency_contact_relation' => 'Pasangan',
                'emergency_contact_phone'    => '081678901299',
                'emergency_contact_address'  => 'Jl. Danau Sunter Utara Blok F No. 12, Jakarta Utara',
                'religion'                   => 'Katolik',
                'marital_status'             => 'married',
                'number_of_dependents'       => 3,
                'blood_type'                 => 'A',
                'medical_conditions'         => 'Tidak ada riwayat penyakit',
                'bank_name'                  => 'BCA',
                'bank_account_no'            => '8830192847',
                'bank_account_holder'        => 'Hendra Gunawan',
                'employment_type'            => 'PKWTT',
                'joined_date'                => '2020-03-15',
            ],
            'super@majubersama.co.id' => [
                'gender'                     => 'Laki-laki',
                'identity_number'            => '3171010101850007',
                'birth_place'                => 'Jakarta',
                'birth_date'                 => '1985-01-01',
                'phone'                      => '081198765407',
                'ktp_address'                => 'Gedung Menara Maju, Jl. Jend. Sudirman Kav. 10, Karet Tengsin',
                'ktp_city'                   => 'Jakarta Pusat',
                'ktp_province'               => 'DKI Jakarta',
                'ktp_postal_code'            => '10220',
                'domicile_address'           => 'Gedung Menara Maju, Jl. Jend. Sudirman Kav. 10, Karet Tengsin',
                'is_domicile_same_as_ktp'    => true,
                'emergency_contact_name'     => 'IT Operations Desk',
                'emergency_contact_relation' => 'Keluarga',
                'emergency_contact_phone'    => '02155551234',
                'emergency_contact_address'  => 'Jl. Jend. Sudirman Kav. 10, Jakarta Pusat',
                'religion'                   => 'Islam',
                'marital_status'             => 'married',
                'number_of_dependents'       => 2,
                'blood_type'                 => 'O',
                'medical_conditions'         => 'Kondisi fisik prima',
                'bank_name'                  => 'BCA',
                'bank_account_no'            => '1000000007',
                'bank_account_holder'        => 'Super Admin',
                'employment_type'            => 'PKWTT',
                'joined_date'                => '2020-01-01',
            ],
            'ricardoabet231@gmail.com' => [
                'gender'                     => 'Laki-laki',
                'identity_number'            => '3174021510980008',
                'birth_place'                => 'Medan',
                'birth_date'                 => '1998-10-15',
                'phone'                      => '081260192808',
                'ktp_address'                => 'Jl. RS Fatmawati Raya No. 45, Cilandak Barat',
                'ktp_city'                   => 'Jakarta Selatan',
                'ktp_province'               => 'DKI Jakarta',
                'ktp_postal_code'            => '12430',
                'domicile_address'           => 'Jl. RS Fatmawati Raya No. 45, Cilandak Barat',
                'is_domicile_same_as_ktp'    => true,
                'emergency_contact_name'     => 'Maria Abet',
                'emergency_contact_relation' => 'Orang Tua',
                'emergency_contact_phone'    => '081260192899',
                'emergency_contact_address'  => 'Jl. RS Fatmawati Raya No. 45, Jakarta Selatan',
                'religion'                   => 'Kristen',
                'marital_status'             => 'single',
                'number_of_dependents'       => 0,
                'blood_type'                 => 'B',
                'medical_conditions'         => 'Tidak ada riwayat alergi',
                'bank_name'                  => 'BCA',
                'bank_account_no'            => '6041928374',
                'bank_account_holder'        => 'Ricardo Abet',
                'employment_type'            => 'PKWTT',
                'joined_date'                => '2024-02-01',
            ],
            'matius@gmail.com' => [
                'gender'                     => 'Laki-laki',
                'identity_number'            => '3172012004930009',
                'birth_place'                => 'Surakarta',
                'birth_date'                 => '1993-04-20',
                'phone'                      => '081388192009',
                'ktp_address'                => 'Jl. Pluit Kencana No. 88, Pluit, Penjaringan',
                'ktp_city'                   => 'Jakarta Utara',
                'ktp_province'               => 'DKI Jakarta',
                'ktp_postal_code'            => '14450',
                'domicile_address'           => 'Jl. Pluit Kencana No. 88, Pluit, Penjaringan',
                'is_domicile_same_as_ktp'    => true,
                'emergency_contact_name'     => 'Yohanes Matius',
                'emergency_contact_relation' => 'Saudara Kandung',
                'emergency_contact_phone'    => '081388192099',
                'emergency_contact_address'  => 'Jl. Pluit Kencana No. 88, Jakarta Utara',
                'religion'                   => 'Kristen',
                'marital_status'             => 'single',
                'number_of_dependents'       => 0,
                'blood_type'                 => 'O',
                'medical_conditions'         => 'Sehat tanpa catatan medis khusus',
                'bank_name'                  => 'Bank Mandiri',
                'bank_account_no'            => '1570019283741',
                'bank_account_holder'        => 'Matius',
                'employment_type'            => 'PKWTT',
                'joined_date'                => '2023-09-01',
            ],
            'joko.semarang@majubersama.co.id' => [
                'gender'                     => 'Laki-laki',
                'identity_number'            => '3374011708920011',
                'birth_place'                => 'Semarang',
                'birth_date'                 => '1992-08-17',
                'phone'                      => '081390123411',
                'ktp_address'                => 'Jl. Pandanaran No. 56, Mugassari, Semarang Selatan',
                'ktp_city'                   => 'Semarang',
                'ktp_province'               => 'Jawa Tengah',
                'ktp_postal_code'            => '50249',
                'domicile_address'           => 'Jl. Pandanaran No. 56, Mugassari, Semarang Selatan',
                'is_domicile_same_as_ktp'    => true,
                'emergency_contact_name'     => 'Sri Santoso',
                'emergency_contact_relation' => 'Pasangan',
                'emergency_contact_phone'    => '081390987611',
                'emergency_contact_address'  => 'Jl. Pandanaran No. 56, Semarang',
                'religion'                   => 'Islam',
                'marital_status'             => 'married',
                'number_of_dependents'       => 1,
                'blood_type'                 => 'A',
                'medical_conditions'         => 'Tidak ada riwayat penyakit',
                'bank_name'                  => 'BRI',
                'bank_account_no'            => '008301029384501',
                'bank_account_holder'        => 'Joko Santoso',
                'employment_type'            => 'PKWTT',
                'joined_date'                => '2023-06-01',
            ],
            'ratih.semarang@majubersama.co.id' => [
                'gender'                     => 'Perempuan',
                'identity_number'            => '3374025205960012',
                'birth_place'                => 'Semarang',
                'birth_date'                 => '1996-05-12',
                'phone'                      => '081390123412',
                'ktp_address'                => 'Jl. Pemuda No. 110, Sekayu, Semarang Tengah',
                'ktp_city'                   => 'Semarang',
                'ktp_province'               => 'Jawa Tengah',
                'ktp_postal_code'            => '50132',
                'domicile_address'           => 'Jl. Pemuda No. 110, Sekayu, Semarang Tengah',
                'is_domicile_same_as_ktp'    => true,
                'emergency_contact_name'     => 'Joko Kumala',
                'emergency_contact_relation' => 'Saudara Kandung',
                'emergency_contact_phone'    => '081390887712',
                'emergency_contact_address'  => 'Jl. Pemuda No. 110, Semarang',
                'religion'                   => 'Islam',
                'marital_status'             => 'single',
                'number_of_dependents'       => 0,
                'blood_type'                 => 'B',
                'medical_conditions'         => 'Sehat jasmani dan rohani',
                'bank_name'                  => 'Bank Mandiri',
                'bank_account_no'            => '1360019284752',
                'bank_account_holder'        => 'Ratih Kumala',
                'employment_type'            => 'PKWT',
                'joined_date'                => '2024-03-01',
            ],
            'agus.semarang@majubersama.co.id' => [
                'gender'                     => 'Laki-laki',
                'identity_number'            => '3374032811900013',
                'birth_place'                => 'Kendal',
                'birth_date'                 => '1990-11-28',
                'phone'                      => '081390123413',
                'ktp_address'                => 'Jl. Gajah Mada No. 89, Kembangsari, Semarang Tengah',
                'ktp_city'                   => 'Semarang',
                'ktp_province'               => 'Jawa Tengah',
                'ktp_postal_code'            => '50133',
                'domicile_address'           => 'Jl. Gajah Mada No. 89, Kembangsari, Semarang Tengah',
                'is_domicile_same_as_ktp'    => true,
                'emergency_contact_name'     => 'Nurul Wibowo',
                'emergency_contact_relation' => 'Pasangan',
                'emergency_contact_phone'    => '081390665513',
                'emergency_contact_address'  => 'Jl. Gajah Mada No. 89, Semarang',
                'religion'                   => 'Islam',
                'marital_status'             => 'married',
                'number_of_dependents'       => 2,
                'blood_type'                 => 'O',
                'medical_conditions'         => 'Riwayat vertigo ringan bila kelelahan',
                'bank_name'                  => 'BCA',
                'bank_account_no'            => '0092817463',
                'bank_account_holder'        => 'Agus Wibowo',
                'employment_type'            => 'PKWTT',
                'joined_date'                => '2022-10-15',
            ],
            'abet@gmail.com' => [
                'gender'                     => 'Laki-laki',
                'identity_number'            => '3174031402970014',
                'birth_place'                => 'Jakarta',
                'birth_date'                 => '1997-02-14',
                'phone'                      => '081298765414',
                'ktp_address'                => 'Jl. Kramat Pela No. 20, Kebayoran Baru',
                'ktp_city'                   => 'Jakarta Selatan',
                'ktp_province'               => 'DKI Jakarta',
                'ktp_postal_code'            => '12130',
                'domicile_address'           => 'Jl. Kramat Pela No. 20, Kebayoran Baru',
                'is_domicile_same_as_ktp'    => true,
                'emergency_contact_name'     => 'David Abet',
                'emergency_contact_relation' => 'Keluarga',
                'emergency_contact_phone'    => '081298765499',
                'emergency_contact_address'  => 'Jl. Kramat Pela No. 20, Jakarta Selatan',
                'religion'                   => 'Kristen',
                'marital_status'             => 'single',
                'number_of_dependents'       => 0,
                'blood_type'                 => 'A',
                'medical_conditions'         => 'Sehat tanpa keluhan',
                'bank_name'                  => 'BCA',
                'bank_account_no'            => '6049281720',
                'bank_account_holder'        => 'Sadawdada',
                'employment_type'            => 'PKWTT',
                'joined_date'                => '2024-05-01',
            ],
            'hacker.cyber231@gmail.com' => [
                'gender'                     => 'Laki-laki',
                'identity_number'            => '3171012602050015',
                'birth_place'                => 'Jakarta',
                'birth_date'                 => '2005-02-26',
                'phone'                      => '081298765415',
                'ktp_address'                => 'Jl. Palmerah Barat No. 50, Palmerah',
                'ktp_city'                   => 'Jakarta Barat',
                'ktp_province'               => 'DKI Jakarta',
                'ktp_postal_code'            => '11480',
                'domicile_address'           => 'Jl. Palmerah Barat No. 50, Palmerah',
                'is_domicile_same_as_ktp'    => true,
                'emergency_contact_name'     => 'Hendra Vidi',
                'emergency_contact_relation' => 'Keluarga',
                'emergency_contact_phone'    => '081298765488',
                'emergency_contact_address'  => 'Jl. Palmerah Barat No. 50, Jakarta Barat',
                'religion'                   => 'Islam',
                'marital_status'             => 'single',
                'number_of_dependents'       => 0,
                'blood_type'                 => 'B',
                'medical_conditions'         => 'Sehat',
                'bank_name'                  => 'BCA',
                'bank_account_no'            => '5221984720',
                'bank_account_holder'        => 'Vidi',
                'employment_type'            => 'PKWTT',
                'joined_date'                => '2025-01-05',
            ],
        ];

        foreach ($userDataMap as $email => $data) {
            $user = User::where('email', $email)->first();
            if ($user) {
                $user->update($data);
                $this->command?->info("✓ Profil diperbarui untuk: {$user->name} ({$email})");
            }
        }

        // 2. Tambah Karyawan Pengujian Proteksi K3 (Di Bawah 17 Tahun & Ibu Hamil)
        // Kasus A: Pekerja Magang Berusia 16 Tahun (Untuk pengujian validasi K3 shift malam < 17 tahun)
        $minorUser = User::firstOrCreate(
            ['email' => 'dimas.magang@majubersama.co.id'],
            [
                'company_id'                 => $company->id,
                'name'                       => 'Dimas Aditya (Magang)',
                'password'                   => Hash::make('Maju2026!'),
                'role'                       => 'employee',
                'employee_code'              => 'EMP-015',
                'department'                 => 'IT',
                'attendance_setting_id'      => 1, // Kantor Pusat Jakarta
                'attendance_enabled'         => true,
                'is_active'                  => true,
                'gender'                     => 'Laki-laki',
                'identity_number'            => '3171011204100016',
                'birth_place'                => 'Jakarta',
                'birth_date'                 => '2010-04-12', // 16 Tahun (Di bawah 17)
                'phone'                      => '081298765416',
                'ktp_address'                => 'Jl. Rawamangun Muka No. 15, RT 02/RW 04, Pulo Gadung',
                'ktp_city'                   => 'Jakarta Timur',
                'ktp_province'               => 'DKI Jakarta',
                'ktp_postal_code'            => '13220',
                'domicile_address'           => 'Jl. Rawamangun Muka No. 15, RT 02/RW 04, Pulo Gadung',
                'is_domicile_same_as_ktp'    => true,
                'emergency_contact_name'     => 'Surya Aditya',
                'emergency_contact_relation' => 'Orang Tua',
                'emergency_contact_phone'    => '081298765477',
                'emergency_contact_address'  => 'Jl. Rawamangun Muka No. 15, Jakarta Timur',
                'religion'                   => 'Islam',
                'marital_status'             => 'single',
                'number_of_dependents'       => 0,
                'blood_type'                 => 'A',
                'medical_conditions'         => 'Tidak ada riwayat penyakit kronis (Siswa Magang SMK)',
                'bank_name'                  => 'BCA',
                'bank_account_no'            => '8810293847',
                'bank_account_holder'        => 'Dimas Aditya',
                'employment_type'            => 'Internship',
                'joined_date'                => '2026-01-15',
            ]
        );
        $this->command?->info("✓ Karyawan uji K3 (<17 th) siap: {$minorUser->name}");

        // Kasus B: Pekerja Hamil (Untuk pengujian validasi K3 shift malam UU No. 13/2003 Pasal 76 ayat 1)
        $pregnantUser = User::firstOrCreate(
            ['email' => 'nadia.putri@majubersama.co.id'],
            [
                'company_id'                 => $company->id,
                'name'                       => 'Nadia Putri',
                'password'                   => Hash::make('Maju2026!'),
                'role'                       => 'employee',
                'employee_code'              => 'EMP-016',
                'department'                 => 'Finance',
                'attendance_setting_id'      => 1, // Kantor Pusat Jakarta
                'attendance_enabled'         => true,
                'is_active'                  => true,
                'gender'                     => 'Perempuan',
                'is_pregnant'                => true, // Tercatat Hamil
                'identity_number'            => '3171026008990017', // 20 + 40 = 60
                'birth_place'                => 'Jakarta',
                'birth_date'                 => '1999-08-20', // 27 Tahun
                'phone'                      => '081298765417',
                'ktp_address'                => 'Jl. Tebet Timur Dalam VI No. 8, RT 05/RW 03, Tebet Timur',
                'ktp_city'                   => 'Jakarta Selatan',
                'ktp_province'               => 'DKI Jakarta',
                'ktp_postal_code'            => '12820',
                'domicile_address'           => 'Jl. Tebet Timur Dalam VI No. 8, RT 05/RW 03, Tebet Timur',
                'is_domicile_same_as_ktp'    => true,
                'emergency_contact_name'     => 'Rizky Pratama',
                'emergency_contact_relation' => 'Pasangan',
                'emergency_contact_phone'    => '081298765466',
                'emergency_contact_address'  => 'Jl. Tebet Timur Dalam VI No. 8, Jakarta Selatan',
                'religion'                   => 'Islam',
                'marital_status'             => 'married',
                'number_of_dependents'       => 0,
                'blood_type'                 => 'O',
                'medical_conditions'         => 'Sedang mengandung usia kehamilan 4 bulan (K3 Proteksi Hamil)',
                'bank_name'                  => 'Bank Mandiri',
                'bank_account_no'            => '1220019284758',
                'bank_account_holder'        => 'Nadia Putri',
                'employment_type'            => 'PKWT',
                'joined_date'                => '2024-04-01',
            ]
        );
        $this->command?->info("✓ Karyawan uji K3 (Hamil) siap: {$pregnantUser->name}");
    }
}
