<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Master Katalog Jenis Cuti Tambahan (Regulasi Pemerintah & Kebijakan Kantor)
    |--------------------------------------------------------------------------
    |
    | Berisi konfigurasi default untuk jenis cuti tambahan di luar jenis cuti
    | standar ('cuti', 'izin', 'sakit', 'wfh').
    |
    | Setiap kantor (AttendanceSetting) dapat mengaktifkan/menonaktifkan (is_enabled)
    | serta menyesuaikan jumlah kuota (quota_days) dan kewajiban lampiran dokumen
    | melalui tabel 'leave_type_settings'.
    |
    */

    'catalog' => [
        'sakit' => [
            'label'                 => 'Cuti Sakit',
            'default_quota_days'    => 14,
            'default_enabled'       => true,
            'gender_restriction'    => null,
            'marital_restriction'   => null,
            'pregnancy_restriction' => false,
            'family_related'        => false,
            'requires_document'     => true,
            'legal_basis'           => 'UU No. 13/2003 Pasal 93 ayat (2) huruf a jo. ayat (3)',
            'description'           => 'Istirahat karena sakit dengan surat keterangan dokter (upah tetap dibayar penuh/sesuai regulasi ketenagakerjaan).',
            'eligibility_notes'     => 'Dapat diajukan oleh seluruh karyawan dengan melampirkan Surat Keterangan Dokter yang sah.',
        ],
        'cuti_hamil' => [
            'label'                 => 'Cuti Hamil & Melahirkan',
            'default_quota_days'    => 90,
            'default_enabled'       => true,
            'gender_restriction'    => 'Perempuan',
            'marital_restriction'   => 'married',
            'pregnancy_restriction' => true,
            'family_related'        => true,
            'requires_document'     => true,
            'legal_basis'           => 'UU No. 13/2003 Ps. 82 (1) jo. UU KIA No. 4/2024',
            'description'           => 'Istirahat 1,5 bulan sebelum melahirkan dan 1,5 bulan setelah melahirkan (dapat diperpanjang hingga 6 bulan jika ada indikasi medis).',
            'eligibility_notes'     => 'Khusus karyawati perempuan yang sudah menikah sah dan berstatus hamil aktif pada data master karyawan.',
        ],
        'cuti_keguguran' => [
            'label'                 => 'Cuti Keguguran',
            'default_quota_days'    => 45,
            'default_enabled'       => true,
            'gender_restriction'    => 'Perempuan',
            'marital_restriction'   => 'married',
            'pregnancy_restriction' => false,
            'family_related'        => true,
            'requires_document'     => true,
            'legal_basis'           => 'UU No. 13/2003 Pasal 82 ayat (2)',
            'description'           => 'Istirahat 1,5 bulan atau sesuai surat keterangan dokter kandungan/bidan setelah keguguran kandungan.',
            'eligibility_notes'     => 'Khusus karyawati perempuan yang berstatus menikah dan mengalami keguguran kandungan (wajib surat dokter kandungan).',
        ],
        'cuti_ayah' => [
            'label'                 => 'Cuti Ayah (Istri Melahirkan / Keguguran)',
            'default_quota_days'    => 2,
            'default_enabled'       => true,
            'gender_restriction'    => 'Laki-laki',
            'marital_restriction'   => 'married',
            'pregnancy_restriction' => false,
            'family_related'        => true,
            'requires_document'     => false,
            'legal_basis'           => 'UU No. 13/2003 Pasal 93 ayat (4) huruf e',
            'description'           => 'Pendampingan suami saat istri sah melahirkan atau mengalami keguguran kandungan.',
            'eligibility_notes'     => 'Khusus karyawan laki-laki yang sudah berstatus menikah pada data karyawan.',
        ],
        'cuti_haid' => [
            'label'                 => 'Cuti Haid',
            'default_quota_days'    => 2,
            'default_enabled'       => true,
            'gender_restriction'    => 'Perempuan',
            'marital_restriction'   => null,
            'pregnancy_restriction' => false,
            'family_related'        => false,
            'requires_document'     => false,
            'legal_basis'           => 'UU No. 13/2003 Pasal 81 ayat (1)',
            'description'           => 'Pekerja perempuan yang merasakan sakit fisik pada hari pertama dan kedua masa haid.',
            'eligibility_notes'     => 'Khusus pekerja perempuan (bisa lajang maupun menikah).',
        ],
        'cuti_menikah' => [
            'label'                 => 'Cuti Menikah',
            'default_quota_days'    => 3,
            'default_enabled'       => true,
            'gender_restriction'    => null,
            'marital_restriction'   => null,
            'pregnancy_restriction' => false,
            'family_related'        => false,
            'requires_document'     => false,
            'legal_basis'           => 'UU No. 13/2003 Pasal 93 ayat (4) huruf a',
            'description'           => 'Pernikahan pekerja/buruh yang bersangkutan (3 hari kerja).',
            'eligibility_notes'     => 'Dapat diajukan oleh seluruh karyawan yang melangsungkan akad atau pemberkatan pernikahan.',
        ],
        'cuti_menikahkan_anak' => [
            'label'                 => 'Menikahkan Anak',
            'default_quota_days'    => 2,
            'default_enabled'       => true,
            'gender_restriction'    => null,
            'marital_restriction'   => 'married',
            'pregnancy_restriction' => false,
            'family_related'        => true,
            'requires_document'     => false,
            'legal_basis'           => 'UU No. 13/2003 Pasal 93 ayat (4) huruf b',
            'description'           => 'Pekerja/buruh menikahkan anak kandung.',
            'eligibility_notes'     => 'Khusus karyawan yang sudah menikah/berkeluarga untuk menikahkan anak.',
        ],
        'cuti_khitan_baptis_anak' => [
            'label'                 => 'Mengkhitankan / Membaptiskan Anak',
            'default_quota_days'    => 2,
            'default_enabled'       => true,
            'gender_restriction'    => null,
            'marital_restriction'   => 'married',
            'pregnancy_restriction' => false,
            'family_related'        => true,
            'requires_document'     => false,
            'legal_basis'           => 'UU No. 13/2003 Pasal 93 ayat (4) huruf c',
            'description'           => 'Pekerja/buruh mengkhitankan atau membaptiskan anak kandung.',
            'eligibility_notes'     => 'Khusus karyawan yang sudah menikah/berkeluarga untuk upacara khitan atau baptis anak.',
        ],
        'cuti_duka_keluarga_inti' => [
            'label'                 => 'Duka Keluarga Inti',
            'default_quota_days'    => 2,
            'default_enabled'       => true,
            'gender_restriction'    => null,
            'marital_restriction'   => null,
            'pregnancy_restriction' => false,
            'family_related'        => true,
            'requires_document'     => false,
            'legal_basis'           => 'UU No. 13/2003 Pasal 93 ayat (4) huruf d',
            'description'           => 'Suami/istri, orang tua/mertua, atau anak pekerja/buruh meninggal dunia.',
            'eligibility_notes'     => 'Dapat diajukan oleh seluruh karyawan saat anggota keluarga inti wafat.',
        ],
        'cuti_duka_serumah' => [
            'label'                 => 'Duka Anggota Serumah',
            'default_quota_days'    => 1,
            'default_enabled'       => true,
            'gender_restriction'    => null,
            'marital_restriction'   => null,
            'pregnancy_restriction' => false,
            'family_related'        => true,
            'requires_document'     => false,
            'legal_basis'           => 'UU No. 13/2003 Pasal 93 ayat (4) huruf f',
            'description'           => 'Anggota keluarga yang berdomisili dalam satu rumah meninggal dunia.',
            'eligibility_notes'     => 'Dapat diajukan oleh seluruh karyawan bila anggota keluarga serumah wafat.',
        ],
        'cuti_ibadah_haji_umrah' => [
            'label'                 => 'Ibadah Keagamaan (Haji / Umrah)',
            'default_quota_days'    => 40,
            'default_enabled'       => true,
            'gender_restriction'    => null,
            'marital_restriction'   => null,
            'pregnancy_restriction' => false,
            'family_related'        => false,
            'requires_document'     => true,
            'legal_basis'           => 'UU No. 13/2003 Ps. 80 & Ps. 93 (2) huruf e',
            'description'           => 'Kewajiban ibadah keagamaan haji/umrah yang diperintahkan agamanya.',
            'eligibility_notes'     => 'Dapat diajukan oleh seluruh karyawan dengan melampirkan bukti keberangkatan resmi.',
        ],
        'cuti_setengah_hari' => [
            'label'                 => 'Cuti Setengah Hari',
            'default_quota_days'    => 10,
            'default_enabled'       => false, // Opt-in per regulasi kantor masing-masing
            'gender_restriction'    => null,
            'marital_restriction'   => null,
            'pregnancy_restriction' => false,
            'family_related'        => false,
            'requires_document'     => false,
            'legal_basis'           => 'Kebijakan Perusahaan / Perjanjian Kerja Bersama',
            'description'           => 'Cuti mandiri berkuota tahunan independen untuk keperluan mendesak setengah hari kerja.',
            'eligibility_notes'     => 'Berlaku jika diaktifkan oleh kantor cabang bersangkutan (kebijakan internal).',
        ],
    ],
];
